
name: CI & Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js (frontend)
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    - name: Install dependencies & build frontend
      run: |
        cd frontend
        npm ci
        npm run build

    - name: Install dependencies & test backend
      run: |
        cd backend
        npm ci
        npm test || echo "No tests found"

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Frontend to Vercel
        run: |
          cd frontend
          npm i -g vercel
          vercel --prod --token ${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Backend to Render
        run: |
          curl -X POST \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            https://api.render.com/deploy/srv-<YOUR_SERVICE_ID>
